### ISSUE TITLE
Target Version

### ISSUE THREAD

**Issue by KyleKing** [sbriand/redmine_wiki_issue_fields#1]
How do I get the value for the field target version?

I've tried: `{{issue_fields(3, target_version)}}`

```Error executing the issue_fields macro (undefined method `target_version' for #<Issue:0x00007f046cd5c100>)```

It looks like target_version should be handled: https://github.com/sbriand/redmine_wiki_issue_fields/blob/master/lib/wiki_issue_fields.rb#L189

**Comment by sbriand** [comment]
Hello

The correction is available in release 0.6.1 of the plugin.
Tested only on Redmine 4.x, but should be ok on Redmine 3.x
