### ISSUE TITLE
Error undefined method `deep_symbolize_keys' for "vide":String when start 

### ISSUE THREAD

**Issue by tantic** [sbriand/redmine_wiki_issue_fields#2]
Hello,

I think that this plugin answer to my need but when I try to install it and restart Redmine i got this message 

```
Completed 500 Internal Server Error in 842ms (ActiveRecord: 3.8ms)


  
NoMethodError (undefined method `deep_symbolize_keys' for "vide":String):
  
lib/redmine/i18n.rb:111:in `valid_languages'
lib/redmine/i18n.rb:136:in `find_language'
app/controllers/application_controller.rb:206:in `set_localization'

```

My environment
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.4.6-p354 (2019-04-01) [x86_64-linux]
  Rails version                  5.2.4.2

Thanks!

**Comment by sbriand** [comment]
Hello

The plugin has not been test on releases 4.x of Redmine.
I am currently migrating my working Redmine from 3.3 to 4.1, so I will be able to reproduce your issue,
and to correct it.

It will come in coming days, I hope.

Regards

Stéphane

**Comment by carterb23** [comment]
`I am currently migrating my working Redmine from 3.3 to 4.1, so I will be able to reproduce your issue,
and to correct it.`

Hi Stéphane, did I get your comment right? Are you planing to make the plugin available for 4.x soon? Would be great. I used it intensively under 3.x and now most of my wikis are broken. I really appreciate your work!

**Comment by sbriand** [comment]
Hello

yes you are right.
I will soon update the plugin for 4.x. I also plan to change its behavior, to work with HTML editor as well as Textile.
Unfortunately, I can not tell when it will be available, because I am quiet busy on other topics.

**Comment by carterb23** [comment]
Great news. Could you also think of making it in a first step available for 4.x and have the HTML editor as feature request or would you prefer combining the tasks. I'm currently setting up a new project, where your plugin would fit perfect. Thanks again!

**Comment by sbriand** [comment]
Hello

Sorry for the delay, I was busy on other topics.
Now, I have setup the new release of Redmine 4.1.1, and reproduced the issue.
This is a stupid and weird bug. The plugin that was working on a 3.x release of Redmine, cause a fatal issue on 4.x,
due to the lack of 2 space characters in the language file, fr.yml.

I have done the correction and pushed a new release 0.6.0 of the plugin.

Regards

Stéphane

**Comment by tantic** [comment]
Thanks for your patch and your reactivity, 
it seems to work fine, i managed to install it, and test it. Now i need to use it a bit more.
I just have these messages when i start the server

```
/app/helpers/application_helper.rb:193: warning: already initialized constant ApplicationHelper::RECORD_LINK
/app/helpers/application_helper.rb:193: warning: previous definition of RECORD_LINK was here
/app/helpers/application_helper.rb:212: warning: already initialized constant ApplicationHelper::ATTACHMENT_CONTAINER_LINK
/app/helpers/application_helper.rb:212: warning: previous definition of ATTACHMENT_CONTAINER_LINK was here
/app/helpers/application_helper.rb:1166: warning: already initialized constant ApplicationHelper::LINKS_RE
/app/helpers/application_helper.rb:1166: warning: previous definition of LINKS_RE was here
/app/helpers/issues_helper.rb:407: warning: already initialized constant IssuesHelper::MultipleValuesDetail
/app/helpers/issues_helper.rb:407: warning: previous definition of MultipleValuesDetail was here

```

Thanks a lot!
